### ISSUE TITLE
Extension error during build

### ISSUE THREAD

**Issue by Darth-Carrotpie** [GDSCParulUniversity/flutter-devcontainer#3]
Getting an error during container build:

```
Error: Failed Installing Extensions: lizebang.bash-extension-pack
    at a.installExtensions (/vscode/vscode-server/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/server/node/server.main.js:144:9986)
```
Removing the extension from `devcontainer.json` solves the error.

**Comment by SaicharanKandukuri** [comment]
Yep, looks like lizebang.bash-extension-pack is removed from vscode marketplace. This will be removed or replaced in next PR. Thanks for the issue @Darth-Carrotpie 
> https://marketplace.visualstudio.com/search?term=lizebang.bash-extension-pack&target=VSCode&category=All%20categories&sortBy=Relevance
